### ISSUE TITLE
Sculk Shrieker in Minimal Skyblock map not spawning warden

### ISSUE THREAD

**Issue by PichuPenguin** [PyjamaMole/Skyblock#1]
In minecraft, by default a sculk shrieker placed post-generation doesn't spawn a warden no matter what, I suggest replacing this item with a warden spawn egg, thus requiring the player to kill it for a sculk catalyst, which can also be used to get infinite sculk shriekers, catalysts, sensors and skulk blocks.

ps. when playing this map (without the sapling and dirt) the only way I could figure out to progress is to wait IRL days to get enough amethyst shards from the budding amethyst to bridge out far enough away to start mob spawning. And as far as I know, your suggestion to replace the sapling and dirt with a composter doesn't help with progression as a composter could only get bone meal which cant be used to make bone blocks without a crafting table (as far as I know)

**Comment by PyjamaMole** [comment]
Im so sorry I missed your comment, the shrieker should have an NBT tag allowing it to spawn wardens, I believe I accidentally included a normal shrieker in the very first edition of the map.

As for starting without any items, yes you would have to wait for the amethyst to grow and make amethyst blocks. With just a composter you can plant the sweet berries, get bonemeal and use this bonemeal on the nylium blocks to get nether trees for renewable blocks. hope this helps ^^
