### ISSUE TITLE
Long grass not spawning on grass blocks when using bonemeal

### ISSUE THREAD

**Issue by GeorgeBeachy** [PyjamaMole/Skyblock#3]
Hi,

Thanks for the great mod, my friends and I are loving it!
I'm not sure if this is expected or not, but when we use bonemeal on grass blocks, no long grass is spawning.
We are running Minecraft/Fabric 1.20.4 with mod version 1.9.0 with entities.

Many thanks,
George

**Comment by GeorgeBeachy** [comment]
Further info:
We are in a plains biome at Y 64 with good lighting.
I have attempted this at Y 4 on a flat world and I have the same issue.
I do not have the issue at either level on vanilla Minecreaft.

**Comment by PyjamaMole** [comment]
This is definitely not intended and have a feeling I might know where the issue lies. 
Will try to fix it as soon as possible, thanks for letting me know ^-^

**Comment by PyjamaMole** [comment]
uploaded a new version that should have fixed the issue
