### ISSUE TITLE
Server Support

### ISSUE THREAD

**Issue by Aurelienhs** [PyjamaMole/Skyblock#4]
On https://modrinth.com/mod/basicskyblock, it says the mod is compatible for both client and server. However, I haven't been able to make it work on a server.

Is this possible to play this mod with friends on a server? If not, will there be server support in the future?

**Comment by PyjamaMole** [comment]
It should just work on a server. I just set up a small test server on my own pc to test and everything seemed fine. 
Which specific version are you using? And are you sure you are running the fabric server jar and not the vanilla minecraft server jar?

**Comment by Aurelienhs** [comment]
I was running the paper jar and since changed it.
Now I'm experiencing issues with the platform on which I host my server, for which I've created a ticket.
I put the mod on my client as well as the server, is this the correct way?

**Comment by PyjamaMole** [comment]
If you're playing on a server the mod doesn't do anything when installed on the client, as all chunk generation is handled by the server. Its however not an issue to have it installed on the client as well, it will just never get loaded when playing.

**Comment by Aurelienhs** [comment]
Thanks, the mod works perfectly!
